// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOAl2YCnjA1TsFSeoEJmRQjnL5nZAWaBw',
    appId: '1:770653682648:web:9352e26b6561dda19ad0ad',
    messagingSenderId: '770653682648',
    projectId: 'inventory-app-738a3',
    authDomain: 'inventory-app-738a3.firebaseapp.com',
    storageBucket: 'inventory-app-738a3.firebasestorage.app',
    measurementId: 'G-0RJZG99PYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8SCj6DPiIucv3g9KXJ5EO2hYgT0N2VwI',
    appId: '1:770653682648:android:4d4d07aaa91535ae9ad0ad',
    messagingSenderId: '770653682648',
    projectId: 'inventory-app-738a3',
    storageBucket: 'inventory-app-738a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5DRX2Q4dL1AgqqVAc9dXWdkyyJ36kJkY',
    appId: '1:770653682648:ios:6eba32d5e7a7f71f9ad0ad',
    messagingSenderId: '770653682648',
    projectId: 'inventory-app-738a3',
    storageBucket: 'inventory-app-738a3.firebasestorage.app',
    iosBundleId: 'com.example.inventoryAppAlvin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5DRX2Q4dL1AgqqVAc9dXWdkyyJ36kJkY',
    appId: '1:770653682648:ios:6eba32d5e7a7f71f9ad0ad',
    messagingSenderId: '770653682648',
    projectId: 'inventory-app-738a3',
    storageBucket: 'inventory-app-738a3.firebasestorage.app',
    iosBundleId: 'com.example.inventoryAppAlvin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOAl2YCnjA1TsFSeoEJmRQjnL5nZAWaBw',
    appId: '1:770653682648:web:257722c080eb6a4d9ad0ad',
    messagingSenderId: '770653682648',
    projectId: 'inventory-app-738a3',
    authDomain: 'inventory-app-738a3.firebaseapp.com',
    storageBucket: 'inventory-app-738a3.firebasestorage.app',
    measurementId: 'G-PCH9ZDJFQE',
  );
}
