// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx_RGJ_fotCF3KUzMBDk1VT7BT6Si3MF8',
    appId: '1:142687421444:web:b428cdc57f39ebd5702151',
    messagingSenderId: '142687421444',
    projectId: 'notes-84028',
    authDomain: 'notes-84028.firebaseapp.com',
    storageBucket: 'notes-84028.firebasestorage.app',
    measurementId: 'G-RQJ9ECK4MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5mhFikvpB_vPZMCAKkkitWshYwZKpbKI',
    appId: '1:142687421444:android:46ec3fce5275b91f702151',
    messagingSenderId: '142687421444',
    projectId: 'notes-84028',
    storageBucket: 'notes-84028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxTpO9_YEhar60wLVKfggpFA6ZDGyR4F4',
    appId: '1:142687421444:ios:f6dde94ea1f6be17702151',
    messagingSenderId: '142687421444',
    projectId: 'notes-84028',
    storageBucket: 'notes-84028.firebasestorage.app',
    iosBundleId: 'com.example.flutterNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBepfawKKAmEA4fSDmo0qqUGJt1eZ-5rZ4',
    appId: '1:261420189128:ios:e9094d8398c3be5a6fecfd',
    messagingSenderId: '261420189128',
    projectId: 'notes-28e55',
    storageBucket: 'notes-28e55.firebasestorage.app',
    iosBundleId: 'com.example.flutterNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx_RGJ_fotCF3KUzMBDk1VT7BT6Si3MF8',
    appId: '1:142687421444:web:3bdcf44dc89cb443702151',
    messagingSenderId: '142687421444',
    projectId: 'notes-84028',
    authDomain: 'notes-84028.firebaseapp.com',
    storageBucket: 'notes-84028.firebasestorage.app',
    measurementId: 'G-VGQ5G44LPK',
  );

}